server:
  port: 8083

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: recipe-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yemekTarifi
      username: Java7User
      password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}